"""auto_serial_bridge 协议代码生成器。

读取 config/protocol.yaml，生成：

- MCU 端 C 代码：protocol.h / protocol.c
- ROS 端绑定：generated_config.hpp / generated_bindings.hpp
- 通信协议文档：PROTOCOL_DOC.md

系统消息 Ack/Heartbeat/Handshake 由生成器内置注入，YAML 中只描述业务消息。
"""

import argparse
import hashlib
import io
import os
import re
import sys

import yaml

# ---------------------------------------------------------------------------
# 常量
# ---------------------------------------------------------------------------

# C 类型字节长度映射（代码生成器支持的全部定长类型）
_C_TYPE_SIZES = {
    "uint8_t":  1,
    "uint16_t": 2,
    "uint32_t": 4,
    "int32_t":  4,
    "float":    4,
}

# 框架内置系统消息：不出现在用户 YAML 中，由生成器自动注入。
# 它们只在协议层收发，不映射任何 ROS 话题。
SYSTEM_MESSAGES = (
    {
        'name': 'Ack',
        'id': 0xFD,
        'direction': 'both',
        'debug_log_mode': 'off',
        'notes': '框架内置：可靠消息的确认包，由协议层自动收发。',
        'fields': [
            {'proto': 'acked_id', 'type': 'uint8_t'},
            {'proto': 'ack_seq', 'type': 'uint8_t'},
        ],
    },
    {
        'name': 'Heartbeat',
        'id': 0xFE,
        'direction': 'both',
        'debug_log_mode': 'off',
        'notes': '框架内置：心跳包，对端原样回传 count。',
        'fields': [
            {'proto': 'count', 'type': 'uint32_t'},
        ],
    },
    {
        'name': 'Handshake',
        'id': 0xFF,
        'direction': 'both',
        'debug_log_mode': 'off',
        'notes': '框架内置：握手包，携带协议哈希。',
        'fields': [
            {'proto': 'protocol_hash', 'type': 'uint32_t'},
        ],
    },
)

SYSTEM_MESSAGE_NAMES = {message['name'] for message in SYSTEM_MESSAGES}
RESERVED_IDS = {message['id']: message['name'] for message in SYSTEM_MESSAGES}

C_CPP_KEYWORDS = {
    '_Alignas', '_Alignof', '_Atomic', '_Bool', '_Complex', '_Generic',
    '_Imaginary', '_Noreturn', '_Static_assert', '_Thread_local',
    'alignas', 'alignof', 'and', 'and_eq', 'asm', 'auto', 'bitand', 'bitor',
    'bool', 'break', 'case', 'catch', 'char', 'char16_t', 'char32_t', 'class',
    'compl', 'concept', 'const', 'constexpr', 'const_cast', 'continue', 'co_await',
    'co_return', 'co_yield', 'decltype', 'default', 'delete', 'do', 'double',
    'dynamic_cast', 'else', 'enum', 'explicit', 'export', 'extern', 'false',
    'float', 'for', 'friend', 'goto', 'if', 'inline', 'int', 'long', 'mutable',
    'namespace', 'new', 'noexcept', 'not', 'not_eq', 'nullptr', 'operator', 'or',
    'or_eq', 'private', 'protected', 'public', 'register', 'reinterpret_cast',
    'requires', 'restrict', 'return', 'short', 'signed', 'sizeof', 'static', 'static_assert',
    'static_cast', 'struct', 'switch', 'template', 'this', 'thread_local', 'throw',
    'true', 'try', 'typedef', 'typeid', 'typename', 'union', 'unsigned', 'using',
    'virtual', 'void', 'volatile', 'wchar_t', 'while', 'xor', 'xor_eq',
}


def is_reserved_c_cpp_identifier(name):
    return name in C_CPP_KEYWORDS or name.startswith('__') or (
        len(name) > 1 and name[0] == '_' and name[1].isupper()
    )

GENERATED_NOTICE = "// Auto-generated by scripts/codegen.py from config/protocol.yaml.\n"

MCU_FILE_BANNER = GENERATED_NOTICE + (
    "//\n"
    "// 警告：本文件生成在 build 目录中，清理构建目录（rm -rf build、\n"
    "// colcon build --cmake-clean-first 等）会连同 USER CODE 块中的手写代码一起丢失。\n"
    "// 长期维护的 MCU 业务代码请保存在你的 MCU 工程里，本文件只做集成拷贝。\n"
)


def generate_crc8_table():
    """生成 CRC8 查找表（多项式 0x31）。"""
    polynomial = 0x31
    table = []
    for i in range(256):
        crc = i
        for _ in range(8):
            if crc & 0x80:
                crc = (crc << 1) ^ polynomial
            else:
                crc = crc << 1
        table.append(crc & 0xFF)
    return table


def _crc8_table_lines(indent):
    table = generate_crc8_table()
    lines = []
    for i in range(0, 256, 16):
        row = ", ".join(f"0x{value:02X}" for value in table[i:i + 16])
        lines.append(f"{indent}{row},")
    return "\n".join(lines)


def get_c_type(yaml_type, type_mappings):
    """把 YAML 类型别名解析为 C 类型；不在映射表中时原样返回。"""
    return type_mappings.get(yaml_type, yaml_type)


def merge_messages(config_data):
    """业务消息 + 内置系统消息，统一按 ID 排序后用于生成。"""
    business = config_data.get('messages', []) or []
    injected = [
        dict(message, fields=[dict(field) for field in message['fields']])
        for message in SYSTEM_MESSAGES
    ]
    return sorted(list(business) + injected, key=lambda m: m['id'])


def ros_message_packages(config_data):
    """Return sorted unique package names referenced by ros_msg entries."""
    return sorted({
        message['ros_msg'].split('/', 1)[0]
        for message in config_data.get('messages', []) or []
        if isinstance(message, dict) and isinstance(message.get('ros_msg'), str)
    })


def message_payload_size(message, type_mappings):
    """计算协议结构体 payload 大小，不含 reliable seq。"""
    return sum(
        _C_TYPE_SIZES.get(get_c_type(field['type'], type_mappings), 1)
        for field in message['fields']
    )


def message_wire_payload_size(message, type_mappings):
    """计算链路上传输的 payload 大小，reliable 消息额外包含 1 字节 seq。"""
    base_size = message_payload_size(message, type_mappings)
    if message.get('reliable', False):
        return base_size + 1
    return base_size


# ---------------------------------------------------------------------------
# 协议哈希
# ---------------------------------------------------------------------------

def _protocol_hash_input(config_data):
    """Return only fields that affect the wire protocol or peer contract.

    消息按 ID 排序后纳入哈希，调整 YAML 中的书写顺序不影响协议哈希。
    """
    cfg = config_data.get('config', {})
    type_mappings = config_data.get('type_mappings', {})
    messages = [
        {
            'id': message['id'],
            'direction': message['direction'],
            'reliable': bool(message.get('reliable', False)),
            'field_types': [
                get_c_type(field['type'], type_mappings)
                for field in message.get('fields', [])
            ],
        }
        for message in merge_messages(config_data)
    ]

    return {
        'head_byte_1': cfg['head_byte_1'],
        'head_byte_2': cfg['head_byte_2'],
        'checksum': str(cfg.get('checksum', 'CRC8')).upper(),
        'require_handshake': bool(cfg.get('require_handshake', True)),
        'messages': messages,
    }


def canonicalize_protocol_hash_input(protocol_source):
    """将协议配置规范化为稳定文本，用于计算协议哈希。"""
    if isinstance(protocol_source, str):
        config_data = yaml.safe_load(protocol_source)
    else:
        config_data = protocol_source
    return yaml.safe_dump(
        _protocol_hash_input(config_data),
        sort_keys=True,
        default_flow_style=False,
        allow_unicode=True,
    )


def calculate_protocol_hash(protocol_source):
    """计算 32 位协议哈希，用于握手时校验两端协议一致性。"""
    canonical_content = canonicalize_protocol_hash_input(protocol_source)
    return int(hashlib.md5(canonical_content.encode('utf-8')).hexdigest()[:8], 16)


# ---------------------------------------------------------------------------
# USER CODE 块与文件写入
# ---------------------------------------------------------------------------

def extract_user_code(file_path):
    """从已存在的生成文件中提取 USER CODE 块。"""
    blocks = {}
    if not os.path.exists(file_path):
        return blocks

    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    pattern = re.compile(
        r'/\* USER CODE BEGIN (\w+) \*/(.*?)/\* USER CODE END \1 \*/', re.DOTALL)
    for key, code in pattern.findall(content):
        blocks[key] = code
    return blocks


def render_block(blocks, key):
    """渲染一个 USER CODE 块。"""
    content = blocks.get(key, "\n")
    return f"/* USER CODE BEGIN {key} */{content}/* USER CODE END {key} */\n"


def write_generated_file(output_path, content):
    """UTF-8 原子写入；内容未变化时跳过写入，避免无谓的重新编译。"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    if os.path.exists(output_path):
        with open(output_path, 'r', encoding='utf-8') as f:
            if f.read() == content:
                return
    tmp_path = output_path + '.tmp'
    with open(tmp_path, 'w', encoding='utf-8') as f:
        f.write(content)
    os.replace(tmp_path, output_path)


# ---------------------------------------------------------------------------
# MCU 端生成
# ---------------------------------------------------------------------------

def generate_mcu_header(config, messages, type_mappings, protocol_hash, output_path, user_blocks):
    """生成 MCU 端 C 头文件。"""
    checksum_algo = str(config.get('checksum', 'CRC8')).upper()
    require_handshake = config.get('require_handshake', True)
    ignore_version_mismatch = config.get('ignore_version_mismatch', False)
    strict_heartbeat = config.get('strict_heartbeat', True)
    heartbeat_interval_ms = config.get('heartbeat_interval_ms', 1000)
    heartbeat_timeout_ms = config.get('heartbeat_timeout_ms', 3000)
    reliable_retry_interval_ms = config.get('reliable_retry_interval_ms', 100)
    reliable_max_retries = config.get('reliable_max_retries', 3)

    with io.StringIO() as f:
        f.write(MCU_FILE_BANNER)
        f.write("#pragma once\n")
        f.write("#include <stdint.h>\n")
        f.write("#include <stddef.h>\n")
        f.write("\n")
        f.write(render_block(user_blocks, "Includes"))
        f.write("\n")

        f.write("// 协议哈希校验码\n")
        f.write(f"#define PROTOCOL_HASH 0x{protocol_hash:08X}\n")
        f.write("\n")

        f.write(f"// 校验算法: {checksum_algo}\n")
        f.write(f"#define CHECKSUM_ALGO_{checksum_algo} 1\n")
        f.write("\n")

        f.write("// 握手配置\n")
        f.write(f"#define CFG_REQUIRE_HANDSHAKE {1 if require_handshake else 0}\n")
        f.write(f"#define CFG_IGNORE_VERSION_MISMATCH {1 if ignore_version_mismatch else 0}\n")
        f.write("\n")

        f.write("// 心跳配置（心跳始终开启，由 ROS 端周期发起，MCU 端由协议层自动回包）\n")
        f.write(f"#define CFG_STRICT_HEARTBEAT {1 if strict_heartbeat else 0}\n")
        f.write(f"#define CFG_HEARTBEAT_INTERVAL_MS {heartbeat_interval_ms}\n")
        f.write(f"#define CFG_HEARTBEAT_TIMEOUT_MS {heartbeat_timeout_ms}\n")
        f.write("\n")

        f.write("// 可靠传输配置：MAX_RETRIES 是重复告警阈值，消息在收到 ACK 前持续重试\n")
        f.write(f"#define CFG_RELIABLE_RETRY_INTERVAL_MS {reliable_retry_interval_ms}\n")
        f.write(f"#define CFG_RELIABLE_MAX_RETRIES {reliable_max_retries}\n")
        f.write("\n")

        f.write(render_block(user_blocks, "Private_Defines"))
        f.write("\n")

        f.write("// 帧头定义\n")
        f.write(f"#define FRAME_HEADER1 {config['head_byte_1']}\n")
        f.write(f"#define FRAME_HEADER2 {config['head_byte_2']}\n")
        f.write("\n")

        f.write("// 数据包ID定义\n")
        f.write("typedef enum {\n")
        for msg in messages:
            f.write(f"    PACKET_ID_{msg['name'].upper()} = {msg['id']},\n")
        f.write("} PacketID;\n")
        f.write("\n")

        f.write("#pragma pack(1)\n")
        for msg in messages:
            f.write("typedef struct {\n")
            for field in msg['fields']:
                c_type = get_c_type(field['type'], type_mappings)
                f.write(f"    {c_type} {field['proto']};\n")
            f.write(f"}} Packet_{msg['name']};\n")
            f.write("\n")
        f.write("#pragma pack()\n")
        f.write("\n")

        f.write("// 协议辅助函数声明\n")
        f.write("uint8_t calculate_checksum(const uint8_t* data, size_t len);\n")
        f.write("void protocol_fsm_feed(uint8_t byte);\n")
        f.write("\n")
        f.write("// 用户可覆盖的接收回调与自动生成的发送函数声明\n")
        for msg in messages:
            f.write(f"void on_receive_{msg['name']}(const Packet_{msg['name']}* pkt);\n")
            f.write(f"void send_{msg['name']}(const Packet_{msg['name']}* pkt);\n")
        f.write("\n")

        f.write(render_block(user_blocks, "User_Types"))

        write_generated_file(output_path, f.getvalue())


def generate_mcu_source(config, messages, type_mappings, output_path, user_blocks):
    """生成 MCU 端 C 源文件。

    系统消息（Heartbeat 回包、Handshake 回应、reliable ACK）由协议层 FSM
    自动处理，用户回调只是可选的观察钩子，覆盖它们不会破坏协议行为。
    """
    checksum_algo = str(config.get('checksum', 'CRC8')).upper()
    require_handshake = config.get('require_handshake', True)

    # rx_buffer 仅暂存当前正在解析的单个包 payload。reliable 包会追加 1 字节 seq。
    max_struct_payload = max(message_payload_size(msg, type_mappings) for msg in messages)
    max_wire_payload = max(message_wire_payload_size(msg, type_mappings) for msg in messages)
    mcu_rx_buf_size = max_wire_payload

    with io.StringIO() as f:
        f.write(MCU_FILE_BANNER)
        f.write("#include \"protocol.h\"\n")
        f.write("#include <string.h>\n\n")
        f.write(render_block(user_blocks, "Includes"))
        f.write("\n")

        f.write(f"""
// 解析器状态定义
typedef enum {{
    STATE_WAIT_HEADER1,
    STATE_WAIT_HEADER2,
    STATE_WAIT_ID,
    STATE_WAIT_LEN,
    STATE_WAIT_DATA,
    STATE_WAIT_CRC
}} State;

// 单包 payload 解析缓冲区 (最大结构体 payload={max_struct_payload}, 最大 wire payload={max_wire_payload})
static State rx_state = STATE_WAIT_HEADER1;
static uint8_t rx_buffer[{mcu_rx_buf_size}];
static uint16_t rx_cnt = 0;
static uint8_t rx_data_len = 0;
static uint8_t rx_id = 0;
static uint8_t rx_checksum = 0;

""")

        if checksum_algo == "CRC8":
            f.write("// CRC8 查找表 (多项式 0x31)\n")
            f.write("static const uint8_t CRC8_TABLE[256] = {\n")
            f.write(_crc8_table_lines("    "))
            f.write("\n};\n\n")
            f.write("""// CRC8 校验函数 (查表法, 多项式 0x31)
static uint8_t checksum_update(uint8_t current, uint8_t byte) {
    return CRC8_TABLE[current ^ byte];
}
""")
        elif checksum_algo == "SUM8":
            f.write("""// SUM8 校验函数 (累加和)
static uint8_t checksum_update(uint8_t current, uint8_t byte) {
    return (uint8_t)(current + byte);
}
""")
        elif checksum_algo == "XOR8":
            f.write("""// XOR8 校验函数 (异或)
static uint8_t checksum_update(uint8_t current, uint8_t byte) {
    return current ^ byte;
}
""")
        else:  # NONE
            f.write("""// 无校验
static uint8_t checksum_update(uint8_t current, uint8_t byte) {
    (void)current; (void)byte;
    return 0;
}
""")

        f.write("""
uint8_t calculate_checksum(const uint8_t* data, size_t len) {
    uint8_t cs = 0;
    for (size_t i = 0; i < len; i++) {
        cs = checksum_update(cs, data[i]);
    }
    return cs;
}
""")

        has_reliable = any(m.get('reliable', False) for m in messages)
        if has_reliable:
            f.write("// 可靠传输序列号：ROS 端在 reliable 包 payload 末尾追加 1 字节 seq，\n")
            f.write("// MCU 收到后存入此变量，ACK 回传时携带该 seq 以区分同 ID 的不同版本。\n")
            f.write("static uint8_t g_last_reliable_seq = 0;\n\n")
            f.write("static inline void send_reliable_ack(PacketID id) {\n")
            f.write("    Packet_Ack ack;\n")
            f.write("    ack.acked_id = (uint8_t)id;\n")
            f.write("    ack.ack_seq = g_last_reliable_seq;\n")
            f.write("    send_Ack(&ack);\n")
            f.write("}\n\n")

        f.write("\n")
        f.write(render_block(user_blocks, "Private_Variables"))
        f.write("\n")

        f.write("\n// 用户可选实现的回调钩子。\n")
        f.write("// 系统消息 (Ack/Heartbeat/Handshake) 的协议行为已由 FSM 内置，\n")
        f.write("// 覆盖这些钩子只用于观察，不需要也不应该在其中回包。\n")
        for msg in messages:
            func_name = f"on_receive_{msg['name']}"
            f.write(f"__attribute__((weak)) void {func_name}(const Packet_{msg['name']}* pkt) {{\n")
            f.write("    (void)pkt;\n")
            f.write(render_block(user_blocks, func_name))
            f.write("}\n")

        f.write("\n")
        f.write(render_block(user_blocks, "Code_0"))
        f.write("\n")

        # NONE 算法时跳过校验比较
        if checksum_algo == "NONE":
            crc_check_expr = "1"
        else:
            crc_check_expr = "byte == rx_checksum"

        f.write(f"""
/**
 * @brief 协议解析状态机，在串口中断或轮询中调用此函数处理每个接收到的字节
 * @param byte 接收到的单个字节
 */
void protocol_fsm_feed(uint8_t byte) {{
    switch (rx_state) {{
        case STATE_WAIT_HEADER1:
            if (byte == FRAME_HEADER1) {{
                rx_state = STATE_WAIT_HEADER2;
            }}
            break;

        case STATE_WAIT_HEADER2:
            if (byte == FRAME_HEADER2) {{
                rx_state = STATE_WAIT_ID;
            }} else if (byte != FRAME_HEADER1) {{
                // 若该字节是新的 HEADER1，则停留在本状态继续等待 HEADER2
                rx_state = STATE_WAIT_HEADER1;
            }}
            break;

        case STATE_WAIT_ID:
            rx_id = byte;
            rx_checksum = checksum_update(0, rx_id); // 校验包含 ID
            rx_state = STATE_WAIT_LEN;
            break;

        case STATE_WAIT_LEN:
            if (byte > sizeof(rx_buffer)) {{
                // 超出协议内最大 payload，直接放弃当前候选帧并重新解析该字节
                rx_state = STATE_WAIT_HEADER1;
                protocol_fsm_feed(byte);
                return;
            }}
            rx_data_len = byte;
            rx_checksum = checksum_update(rx_checksum, rx_data_len); // 校验包含 Len
            rx_cnt = 0;
            rx_state = (rx_data_len > 0) ? STATE_WAIT_DATA : STATE_WAIT_CRC;
            break;

        case STATE_WAIT_DATA:
            rx_buffer[rx_cnt++] = byte;
            rx_checksum = checksum_update(rx_checksum, byte);
            if (rx_cnt >= rx_data_len) {{
                rx_state = STATE_WAIT_CRC;
            }}
            break;

        case STATE_WAIT_CRC:
            if ({crc_check_expr}) {{
                // 校验通过，分发数据
                switch (rx_id) {{
""")
        for msg in messages:
            f.write(f"                    case PACKET_ID_{msg['name'].upper()}:\n")
            if msg.get('reliable', False):
                # reliable 包: ROS 端会在 payload 末尾追加 1 字节 seq
                # ACK 在协议层自动发送，用户回调无需关心
                f.write(f"                        if (rx_data_len == sizeof(Packet_{msg['name']}) + 1) {{\n")
                f.write(f"                            on_receive_{msg['name']}((Packet_{msg['name']}*)rx_buffer);\n")
                f.write(f"                            g_last_reliable_seq = rx_buffer[sizeof(Packet_{msg['name']})];\n")
                f.write(f"                            send_reliable_ack(PACKET_ID_{msg['name'].upper()});\n")
                f.write("                        }\n")
            else:
                f.write(f"                        if (rx_data_len == sizeof(Packet_{msg['name']})) {{\n")
                if msg['name'] == 'Heartbeat':
                    f.write("                            // 框架内置：原样回传心跳包作为 ACK\n")
                    f.write("                            send_Heartbeat((const Packet_Heartbeat*)rx_buffer);\n")
                if msg['name'] == 'Handshake' and require_handshake:
                    f.write("                            // 框架内置：回传本机协议哈希，由 ROS 端校验是否匹配\n")
                    f.write("                            {\n")
                    f.write("                                Packet_Handshake handshake_reply;\n")
                    f.write("                                handshake_reply.protocol_hash = PROTOCOL_HASH;\n")
                    f.write("                                send_Handshake(&handshake_reply);\n")
                    f.write("                            }\n")
                f.write(f"                            on_receive_{msg['name']}((Packet_{msg['name']}*)rx_buffer);\n")
                f.write("                        }\n")
            f.write("                        break;\n")

        f.write("""
                    default:
                        break;
                }
            }
            rx_state = STATE_WAIT_HEADER1;
            break;

        default:
            rx_state = STATE_WAIT_HEADER1;
            break;
    }
}
""")

        f.write("\n// --- 发送函数 ---\n")
        f.write("// 外部依赖：用户必须实现 void serial_write(const uint8_t* data, uint16_t len);\n")
        f.write("// 注意：协议层会在 protocol_fsm_feed() 的调用上下文中发送回包（心跳/握手/ACK）。\n")
        f.write("// 若 protocol_fsm_feed() 在中断中调用，而业务代码也在主循环调用 send_xxx()，\n")
        f.write("// 则 serial_write() 必须自行保证可重入/并发安全（如关中断或使用发送队列）。\n")
        f.write("extern void serial_write(const uint8_t* data, uint16_t len);\n\n")

        for msg in messages:
            f.write(f"void send_{msg['name']}(const Packet_{msg['name']}* pkt) {{\n")
            f.write(f"    uint8_t buffer[4 + sizeof(Packet_{msg['name']}) + 1];\n")
            f.write("    uint16_t idx = 0;\n")
            f.write("    \n")
            f.write("    buffer[idx++] = FRAME_HEADER1;\n")
            f.write("    buffer[idx++] = FRAME_HEADER2;\n")
            f.write(f"    buffer[idx++] = PACKET_ID_{msg['name'].upper()};\n")
            f.write(f"    buffer[idx++] = sizeof(Packet_{msg['name']});\n")
            f.write("    \n")
            f.write(f"    memcpy(&buffer[idx], pkt, sizeof(Packet_{msg['name']}));\n")
            f.write(f"    idx += sizeof(Packet_{msg['name']});\n")
            f.write("    \n")
            f.write("    buffer[idx] = calculate_checksum(&buffer[2], idx - 2);\n")
            f.write("    idx++;\n")
            f.write("    \n")
            f.write("    serial_write(buffer, idx);\n")
            f.write("}\n")

        f.write("\n")
        f.write(render_block(user_blocks, "Code_1"))
        f.write("\n")
        f.write("// 心跳由 ROS 端周期发起 (间隔 CFG_HEARTBEAT_INTERVAL_MS)，\n")
        f.write("// 协议层收到后自动原样回包，MCU 侧无需主动发送心跳。\n")
        f.write("\n")

        write_generated_file(output_path, f.getvalue())


# ---------------------------------------------------------------------------
# ROS 端生成
# ---------------------------------------------------------------------------

_ROS_FIELD_SEGMENT_RE = re.compile(r'([A-Za-z_][A-Za-z0-9_]*)(?:\[(\d+)\])?$')


def _merge_vector_requirements(dest, updates):
    for expr, required_size in updates.items():
        dest[expr] = max(dest.get(expr, 0), required_size)


def _vector_label(expr: str) -> str:
    if expr.startswith('msg->'):
        return expr[5:]
    if expr.startswith('msg.'):
        return expr[4:]
    return expr


def _analyze_ros_path(path: str, root_var: str, pointer: bool):
    current_expr = root_var
    access_expr = root_var
    vector_requirements = {}

    for index, segment in enumerate(path.split('.')):
        match = _ROS_FIELD_SEGMENT_RE.fullmatch(segment)
        if not match:
            raise ValueError(f"Unsupported ROS field path segment: {segment!r} in {path!r}")

        name, array_index = match.groups()
        separator = '->' if pointer and index == 0 else '.'
        base_expr = f"{current_expr}{separator}{name}"
        if array_index is not None:
            access_expr = f"{base_expr}[{array_index}]"
            vector_requirements[base_expr] = max(
                vector_requirements.get(base_expr, 0),
                int(array_index) + 1,
            )
        else:
            access_expr = base_expr

        current_expr = access_expr

    return access_expr, vector_requirements


def _needs_int32_multiarray_u8_range_guard(ros_msg: str, field: dict, type_mappings: dict) -> bool:
    return (
        ros_msg == "std_msgs/msg/Int32MultiArray" and
        get_c_type(field['type'], type_mappings) == "uint8_t"
    )


def _write_u8_range_guard(f, msg_name: str, topic: str, field_name: str, read_expr: str) -> None:
    f.write(f"            if ({read_expr} < 0 || {read_expr} > 255) {{\n")
    f.write("                RCLCPP_ERROR_THROTTLE(\n")
    f.write("                    node->get_logger(), *node->get_clock(), 2000,\n")
    f.write(
        f"                    \"Message for {msg_name} on {topic} field {field_name} is out of uint8 range [0, 255]: %d\",\n"
    )
    f.write(f"                    static_cast<int>({read_expr}));\n")
    f.write("                return;\n")
    f.write("            }\n")


def _normalize_debug_log_mode(value) -> str:
    if value is None:
        return "on"
    return str(value).strip().lower()


def _write_guarded_rx_debug_log(f, msg_name: str, fmt_parts, arg_parts) -> None:
    packet_id = f"PACKET_ID_{msg_name.upper()}"
    f.write(f"            if constexpr (config::is_debug_log_enabled({packet_id})) {{\n")
    if fmt_parts:
        fmt_str = ", ".join(fmt_parts)
        args_str = ", ".join(arg_parts)
        f.write(
            f"                RCLCPP_DEBUG(logger, \"RX {msg_name}: {fmt_str}\", {args_str});\n"
        )
    else:
        f.write(
            f"                RCLCPP_DEBUG(logger, \"RX {msg_name}\");\n"
        )
    f.write("            }\n")


def generate_ros_bindings(messages, type_mappings, config, output_path):
    """生成 ROS 端 C++ 绑定代码（自动订阅、发布与分发逻辑）。

    系统消息没有 ROS 话题，只出现在 describe_packet 中；
    订阅/发布/分发只针对带话题的业务消息。
    """
    qos_depth = config.get('qos_depth', 10)

    includes = sorted({
        msg['ros_msg'] for msg in messages if msg.get('ros_msg')
    })

    with io.StringIO() as f:
        f.write(GENERATED_NOTICE)
        f.write("#pragma once\n")
        f.write("#include <cstddef>\n")
        f.write("#include <cstdint>\n")
        f.write("#include <cstring>\n")
        f.write("#include <sstream>\n")
        f.write("#include <string>\n")
        f.write("#include <type_traits>\n")
        f.write("#include <vector>\n")
        f.write("#include \"auto_serial_bridge/generated/generated_config.hpp\"\n")
        f.write("#include \"auto_serial_bridge/serial_controller.hpp\"\n")
        for inc in includes:
            pkg, sub, typ = inc.split('/')
            s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', typ)
            snake_typ = re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()
            f.write(f"#include <{pkg}/{sub}/{snake_typ}.hpp>\n")

        f.write("#include \"auto_serial_bridge/generated/protocol.h\"\n")
        f.write("\n")

        f.write("namespace auto_serial_bridge {\n")
        f.write("namespace generated {\n")
        f.write("\n")

        f.write("""namespace detail {
template <typename T, typename = void>
struct HasResize : std::false_type {};
template <typename T>
struct HasResize<T, std::void_t<decltype(std::declval<T&>().resize(std::size_t{}))>> : std::true_type {};

// 动态容器 (std::vector) 按需扩容；定长容器 (std::array) 只校验容量。
template <typename T>
inline bool ensure_size(T& container, std::size_t required) {
    if constexpr (HasResize<T>::value) {
        if (container.size() < required) {
            container.resize(required);
        }
        return true;
    } else {
        return container.size() >= required;
    }
}
} // namespace detail

""")

        f.write("// MCU TX DECODED helper.\n")
        f.write("inline std::string describe_packet(PacketID id, const std::vector<uint8_t>& payload) {\n")
        f.write("    std::ostringstream out;\n")
        f.write("    switch(id) {\n")
        for msg in messages:
            if msg['direction'] in ('tx', 'both'):
                f.write(f"        case PACKET_ID_{msg['name'].upper()}: {{\n")
                f.write(f"            if (payload.size() < sizeof(Packet_{msg['name']})) {{\n")
                f.write(f"                out << \"{msg['name']}: payload_size=\" << payload.size() << \" expected>=\" << sizeof(Packet_{msg['name']});\n")
                f.write("                return out.str();\n")
                f.write("            }\n")
                f.write(f"            Packet_{msg['name']} pkt;\n")
                f.write("            std::memcpy(&pkt, payload.data(), sizeof(pkt));\n")
                field_parts = []
                for field in msg['fields']:
                    field_name = field['proto']
                    field_type = str(field.get('type', '')).lower()
                    if field_type.startswith('f'):
                        field_parts.append(f' << "{field_name}=" << static_cast<double>(pkt.{field_name})')
                    elif field_type.startswith('u'):
                        field_parts.append(f' << "{field_name}=" << static_cast<unsigned int>(pkt.{field_name})')
                    else:
                        field_parts.append(f' << "{field_name}=" << static_cast<int>(pkt.{field_name})')
                if field_parts:
                    joined = ' << ", "'.join(field_parts)
                    f.write(f"            out << \"{msg['name']}: \"{joined};\n")
                else:
                    f.write(f"            out << \"{msg['name']}\";\n")
                if msg.get('reliable', False):
                    f.write(f"            if (payload.size() > sizeof(Packet_{msg['name']})) {{\n")
                    f.write(f"                out << \", ack_seq=\" << static_cast<unsigned int>(payload[sizeof(Packet_{msg['name']})]);\n")
                    f.write("            }\n")
                f.write("            return out.str();\n")
                f.write("        }\n")
        f.write("        default:\n")
        f.write("            out << \"packet_id=0x\" << std::hex << static_cast<unsigned int>(static_cast<uint8_t>(id)) << std::dec << \", payload_size=\" << payload.size();\n")
        f.write("            return out.str();\n")
        f.write("    }\n")
        f.write("}\n\n")

        f.write("inline void register_all(SerialController* node) {\n")
        f.write("    (void)node;\n")

        for msg in messages:
            topic = msg.get('sub_topic')
            if msg['direction'] not in ('tx', 'both') or not topic:
                continue

            pkg, sub, typ = msg['ros_msg'].split('/')
            ros_type_cpp = f"{pkg}::{sub}::{typ}"

            f.write(f"    // {msg['name']} (ROS -> MCU)\n")
            f.write(f"    node->add_subscription(node->create_subscription<{ros_type_cpp}>(\n")
            f.write(f"        \"{topic}\", {qos_depth},\n")
            f.write(f"        [node](const {ros_type_cpp}::SharedPtr msg) {{\n")

            vector_requirements = {}
            field_reads = []
            for field in msg['fields']:
                read_expr, requirements = _analyze_ros_path(field['ros'], 'msg', True)
                _merge_vector_requirements(vector_requirements, requirements)
                field_reads.append((field, read_expr))

            for expr, required_size in sorted(vector_requirements.items()):
                label = _vector_label(expr)
                f.write(f"            if ({expr}.size() < {required_size}) {{\n")
                f.write("                RCLCPP_ERROR_THROTTLE(\n")
                f.write("                    node->get_logger(), *node->get_clock(), 2000,\n")
                f.write(f"                    \"Message for {msg['name']} on {topic} requires at least {required_size} entries in {label}, got %zu\",\n")
                f.write(f"                    {expr}.size());\n")
                f.write("                return;\n")
                f.write("            }\n")

            f.write(f"            Packet_{msg['name']} pkt;\n")
            for field, read_expr in field_reads:
                c_type = get_c_type(field['type'], type_mappings)
                if _needs_int32_multiarray_u8_range_guard(msg['ros_msg'], field, type_mappings):
                    _write_u8_range_guard(f, msg['name'], topic, field['proto'], read_expr)
                f.write(f"            pkt.{field['proto']} = static_cast<{c_type}>({read_expr});\n")

            send_api = "reliable_send" if msg.get('reliable', False) else "send_packet"
            f.write(f"            node->{send_api}(PACKET_ID_{msg['name'].upper()}, pkt);\n")
            f.write("        }));\n")
            f.write("\n")

        f.write("}\n\n")

        f.write("struct ProtocolPublishers {\n")
        for msg in messages:
            if msg['direction'] in ('rx', 'both') and msg.get('pub_topic'):
                pkg, sub, typ = msg['ros_msg'].split('/')
                f.write(f"    rclcpp::Publisher<{pkg}::{sub}::{typ}>::SharedPtr pub_{msg['name']};\n")

        f.write("\n    void init(SerialController* node) {\n")
        f.write("        (void)node;\n")
        for msg in messages:
            if msg['direction'] in ('rx', 'both') and msg.get('pub_topic'):
                pkg, sub, typ = msg['ros_msg'].split('/')
                f.write(f"        pub_{msg['name']} = node->create_publisher<{pkg}::{sub}::{typ}>(\"{msg['pub_topic']}\", {qos_depth});\n")
        f.write("    }\n")
        f.write("};\n\n")

        f.write("inline void dispatch_packet(ProtocolPublishers& pubs, uint8_t id, const std::vector<uint8_t>& data, const rclcpp::Logger& logger) {\n")
        f.write("    (void)pubs; (void)logger;\n")
        f.write("    switch(id) {\n")
        for msg in messages:
            if msg['direction'] not in ('rx', 'both') or not msg.get('pub_topic'):
                continue
            f.write(f"        case PACKET_ID_{msg['name'].upper()}: {{\n")
            f.write(f"            if (data.size() != sizeof(Packet_{msg['name']})) break;\n")
            f.write(f"            Packet_{msg['name']} pkt;\n")
            f.write("            std::memcpy(&pkt, data.data(), sizeof(pkt));\n")

            pkg, sub, typ = msg['ros_msg'].split('/')
            f.write(f"            auto msg = {pkg}::{sub}::{typ}();\n")
            vector_requirements = {}
            field_writes = []
            for field in msg['fields']:
                write_expr, requirements = _analyze_ros_path(field['ros'], 'msg', False)
                _merge_vector_requirements(vector_requirements, requirements)
                field_writes.append((field, write_expr))
            for expr, required_size in sorted(vector_requirements.items()):
                f.write(f"            if (!detail::ensure_size({expr}, {required_size})) break;\n")
            for field, write_expr in field_writes:
                c_type = get_c_type(field['type'], type_mappings)
                if msg['ros_msg'] == "std_msgs/msg/Int32MultiArray" and c_type == "uint8_t":
                    f.write(f"            {write_expr} = static_cast<int32_t>(pkt.{field['proto']});\n")
                else:
                    f.write(f"            {write_expr} = pkt.{field['proto']};\n")

            fmt_parts = []
            arg_parts = []
            for field in msg['fields']:
                field_name = field['proto']
                field_type = str(field.get('type', '')).lower()
                if field_type.startswith('f'):
                    fmt_parts.append(f"{field_name}=%.3f")
                    arg_parts.append(f"static_cast<double>(pkt.{field_name})")
                elif field_type.startswith('u'):
                    fmt_parts.append(f"{field_name}=%u")
                    arg_parts.append(f"static_cast<unsigned int>(pkt.{field_name})")
                else:
                    fmt_parts.append(f"{field_name}=%d")
                    arg_parts.append(f"static_cast<int>(pkt.{field_name})")

            _write_guarded_rx_debug_log(f, msg['name'], fmt_parts, arg_parts)

            f.write(f"            if (pubs.pub_{msg['name']}) {{\n")
            f.write(f"                pubs.pub_{msg['name']}->publish(msg);\n")
            f.write("            }\n")
            f.write("            break;\n")
            f.write("        }\n")
        f.write("        default:\n")
        f.write("            break;\n")
        f.write("    }\n")
        f.write("}\n")

        f.write("}\n")  # namespace generated
        f.write("}\n")  # namespace auto_serial_bridge

        write_generated_file(output_path, f.getvalue())


def generate_cpp_config(config, messages, type_mappings, output_path, serial_params=None):
    """生成 C++ 公共配置头文件。"""
    checksum_algo = str(config.get('checksum', 'CRC8')).upper()
    require_handshake = config.get('require_handshake', True)
    ignore_version_mismatch = config.get('ignore_version_mismatch', False)
    qos_depth = config.get('qos_depth', 10)
    heartbeat_interval_ms = config.get('heartbeat_interval_ms', 1000)
    heartbeat_timeout_ms = config.get('heartbeat_timeout_ms', 3000)
    strict_heartbeat = config.get('strict_heartbeat', True)
    reliable_retry_interval_ms = config.get('reliable_retry_interval_ms', 100)
    reliable_max_retries = config.get('reliable_max_retries', 3)
    serial_params = serial_params or {}
    default_port = serial_params.get('port', '/dev/ttyACM0')
    default_baudrate = serial_params.get('baudrate', 115200)

    with io.StringIO() as f:
        f.write(GENERATED_NOTICE)
        f.write("#pragma once\n")
        f.write("#include <cstdint>\n")
        f.write("#include <cstddef>\n\n")
        f.write("#include \"auto_serial_bridge/generated/protocol.h\"\n\n")
        f.write("namespace auto_serial_bridge {\n")
        f.write("namespace config {\n\n")

        f.write(f"    constexpr const char * DEFAULT_PORT = \"{default_port}\";\n")
        f.write(f"    constexpr uint32_t DEFAULT_BAUDRATE = {default_baudrate};\n")
        f.write(f"    constexpr size_t BUFFER_SIZE = {config['buffer_size']};\n")
        f.write(f"    constexpr uint8_t CFG_FRAME_HEADER1 = {config['head_byte_1']};\n")
        f.write(f"    constexpr uint8_t CFG_FRAME_HEADER2 = {config['head_byte_2']};\n\n")

        # TODO: 扩展支持 CRC16/CRC32 (需修改帧格式，校验字段从 1 字节增加到 2/4 字节)
        f.write("    enum class ChecksumAlgo { NONE, SUM8, XOR8, CRC8 };\n")
        f.write(f"    constexpr ChecksumAlgo CHECKSUM_ALGO = ChecksumAlgo::{checksum_algo};\n\n")

        f.write("    // CRC8 查找表 (多项式 0x31)。constexpr，未选用 CRC8 时零开销。\n")
        f.write("    inline constexpr uint8_t CRC8_TABLE[256] = {\n")
        f.write(_crc8_table_lines("        "))
        f.write("\n    };\n\n")

        f.write(f"    constexpr bool REQUIRE_HANDSHAKE = {'true' if require_handshake else 'false'};\n")
        f.write(f"    constexpr bool IGNORE_VERSION_MISMATCH = {'true' if ignore_version_mismatch else 'false'};\n")
        f.write(f"    constexpr bool STRICT_HEARTBEAT = {'true' if strict_heartbeat else 'false'};\n")
        f.write(f"    constexpr size_t QOS_DEPTH = {qos_depth};\n")
        f.write(f"    constexpr int HEARTBEAT_INTERVAL_MS = {heartbeat_interval_ms};\n")
        f.write(f"    constexpr int HEARTBEAT_TIMEOUT_MS = {heartbeat_timeout_ms};\n")
        f.write(f"    constexpr int RELIABLE_RETRY_INTERVAL_MS = {reliable_retry_interval_ms};\n")
        f.write(f"    constexpr int RELIABLE_MAX_RETRIES = {reliable_max_retries};\n")
        max_payload_size = max(message_wire_payload_size(msg, type_mappings) for msg in messages)
        f.write(f"    constexpr size_t MAX_PACKET_PAYLOAD_SIZE = {max_payload_size};\n\n")

        f.write("    inline constexpr size_t expected_payload_size(PacketID id) {\n")
        f.write("        switch (id) {\n")
        for msg in messages:
            if msg.get('reliable', False):
                f.write(f"            case PACKET_ID_{msg['name'].upper()}: return sizeof(Packet_{msg['name']}) + 1;\n")
            else:
                f.write(f"            case PACKET_ID_{msg['name'].upper()}: return sizeof(Packet_{msg['name']});\n")
        f.write("            default: return 0;\n")
        f.write("        }\n")
        f.write("    }\n")
        f.write("\n")

        f.write("    inline constexpr bool is_reliable_packet(PacketID id) {\n")
        f.write("        switch (id) {\n")
        for msg in messages:
            reliable = 'true' if msg.get('reliable', False) else 'false'
            f.write(f"            case PACKET_ID_{msg['name'].upper()}: return {reliable};\n")
        f.write("            default: return false;\n")
        f.write("        }\n")
        f.write("    }\n")

        f.write("\n")
        f.write("    inline constexpr bool is_debug_log_enabled(PacketID id) {\n")
        f.write("        switch (id) {\n")
        for msg in messages:
            mode = msg.get('debug_log_mode', 'on')
            enabled = 'false' if mode == 'off' else 'true'
            f.write(f"            case PACKET_ID_{msg['name'].upper()}: return {enabled};\n")
        f.write("            default: return true;\n")
        f.write("        }\n")
        f.write("    }\n")

        f.write("\n}\n")
        f.write("}\n")

        write_generated_file(output_path, f.getvalue())


# ---------------------------------------------------------------------------
# 协议文档生成
# ---------------------------------------------------------------------------

def _field_table(
    fields: list,
    type_mappings: dict,
    checksum_algo: str = "CRC8",
    include_reliable_seq: bool = False,
) -> str:
    """渲染字段信息为 Markdown 表格字符串。"""
    _CHECKSUM_LABELS = {
        "NONE": "无校验 (占位)",
        "SUM8": "SUM8",
        "XOR8": "XOR8",
        "CRC8": "CRC8",
    }
    lines = [
        "| 字节偏移 | 字段名 | C 类型 | 字节数 |",
        "| :------: | :----- | :----- | :----: |",
    ]
    offset = 0
    for field in fields:
        c_type = type_mappings.get(field['type'], field['type'])
        size = _C_TYPE_SIZES.get(c_type, 1)
        lines.append(f"| {offset} | `{field['proto']}` | `{c_type}` | {size} |")
        offset += size
    if include_reliable_seq:
        lines.append(f"| {offset} | *(reliable seq，框架附加，非业务结构体字段)* | `uint8_t` | 1 |")
        offset += 1
    label = _CHECKSUM_LABELS.get(checksum_algo, checksum_algo)
    lines.append(f"| **{offset}** | *({label})* | `uint8_t` | 1 |")
    return "\n".join(lines)


def generate_mcu_doc(config: dict, messages: list, type_mappings: dict,
                     protocol_hash: int, output_path: str,
                     serial_params=None) -> None:
    """生成面向下位机开发者的 Markdown 通信协议文档。"""
    head1 = config['head_byte_1']
    head2 = config['head_byte_2']
    serial_params = serial_params or {}
    baudrate = serial_params.get('baudrate', 115200)
    checksum = str(config.get('checksum', 'CRC8')).upper()
    require_handshake = config.get('require_handshake', True)

    _CHECKSUM_DESC = {
        "NONE": "无校验（占位字节 `0x00`）",
        "SUM8": "SUM8 累加和，覆盖 ID + Len + Data",
        "XOR8": "XOR8 异或，覆盖 ID + Len + Data",
        "CRC8": "CRC8，覆盖 ID + Len + Data，多项式 `0x31`",
    }

    rx_msgs = [m for m in messages if m['direction'] in ('rx', 'both')]   # MCU → ROS
    tx_msgs = [m for m in messages if m['direction'] in ('tx', 'both')]   # ROS → MCU

    def _write_message_meta(f, msg, topic_key):
        topic = msg.get(topic_key)
        if topic:
            f.write(f"- **ROS 话题**：`{topic}`\n")
        if msg.get('ros_msg'):
            f.write(f"- **ROS 消息类型**：`{msg['ros_msg']}`\n")

    with io.StringIO() as f:
        f.write("# MCU ↔ ROS 通信协议文档\n\n")
        f.write("> **Auto-generated** — 由 `scripts/codegen.py` 根据 `config/protocol.yaml` 生成，请勿手动修改。\n\n")
        f.write("---\n\n")

        strict_heartbeat = config.get('strict_heartbeat', True)
        heartbeat_interval_ms = config.get('heartbeat_interval_ms', 1000)
        heartbeat_timeout_ms = config.get('heartbeat_timeout_ms', 3000)
        reliable_retry_interval_ms = config.get('reliable_retry_interval_ms', 100)
        reliable_max_retries = config.get('reliable_max_retries', 3)

        f.write("## 全局参数\n\n")
        f.write("| 参数 | 值 |\n")
        f.write("| :--- | :--- |\n")
        f.write(f"| 波特率 | `{baudrate}` |\n")
        f.write(f"| 帧头字节 1 | `{head1:#04x}` |\n")
        f.write(f"| 帧头字节 2 | `{head2:#04x}` |\n")
        f.write(f"| 校验算法 | `{checksum}` |\n")
        f.write(f"| 强制握手 | `{'是' if require_handshake else '否'}` |\n")
        f.write(f"| 协议哈希（握手用）| `0x{protocol_hash:08X}` |\n")
        f.write(f"| 严格心跳模式 | `{'是' if strict_heartbeat else '否'}` |\n")
        f.write(f"| 心跳发送间隔（ROS 端发起）| `{heartbeat_interval_ms} ms` |\n")
        f.write(f"| 心跳超时时间 | `{heartbeat_timeout_ms} ms` |\n")
        f.write(f"| 可靠传输重试间隔 | `{reliable_retry_interval_ms} ms` |\n")
        f.write(f"| 可靠传输重试告警阈值 | 每 `{reliable_max_retries} 次`告警一次，收到 ACK 前持续重试 |\n")
        f.write("\n---\n\n")

        f.write("## 帧格式\n\n")
        f.write("每帧结构如下（小端序）：\n\n")
        f.write("| 字节位置 | 字段 | 说明 |\n")
        f.write("| :------: | :--- | :--- |\n")
        f.write(f"| 0 | Header1 | 固定 `{head1:#04x}` |\n")
        f.write(f"| 1 | Header2 | 固定 `{head2:#04x}` |\n")
        f.write("| 2 | ID | 消息 ID，见下表 |\n")
        f.write("| 3 | Len | 数据段字节数 |\n")
        f.write("| 4 … 4+Len-1 | Data | 各字段按结构体内存布局排列 |\n")
        checksum_desc = _CHECKSUM_DESC.get(checksum, checksum)
        f.write(f"| 4+Len | Checksum | {checksum_desc} |\n")
        f.write("\n---\n\n")

        f.write("## MCU 集成注意事项\n\n")
        f.write("- 系统消息无需编写代码：心跳回包、握手回应、可靠消息 ACK 均由生成的协议状态机自动完成。\n")
        f.write("- 协议层会在 `protocol_fsm_feed()` 的调用上下文中发送回包。若 `protocol_fsm_feed()` "
                "在串口中断中调用，而业务代码在主循环中调用 `send_xxx()`，"
                "`serial_write()` 必须自行保证可重入/并发安全（如关中断保护或发送队列）。\n")
        f.write("- 心跳由 ROS 端周期发起并在超时窗口内重发同一 `count`，MCU 侧对重复心跳原样回包即可（自动完成）。\n")
        f.write("\n---\n\n")

        f.write("## 电控 → ROS（电控主动发送）\n\n")
        if rx_msgs:
            for msg in rx_msgs:
                total_bytes = message_payload_size(msg, type_mappings)
                f.write(f"### `{msg['name']}` — ID `{msg['id']:#04x}`\n\n")
                _write_message_meta(f, msg, 'pub_topic')
                f.write(f"- **数据段字节数（Len）**：`{total_bytes}`\n")
                if msg.get('notes'):
                    f.write(f"- **注意事项**：{msg['notes']}\n")
                if msg['name'] == 'Handshake' and require_handshake:
                    f.write("- **内置行为**：协议层收到握手包后自动回传本机 `PROTOCOL_HASH`，是否匹配由 ROS 端校验，MCU 侧无需编写代码。\n")
                f.write("\n")
                f.write(_field_table(msg['fields'], type_mappings, checksum))
                f.write("\n\n")
        else:
            f.write("_无_\n\n")

        f.write("---\n\n")

        f.write("## ROS → 电控（电控被动接收）\n\n")
        if tx_msgs:
            for msg in tx_msgs:
                reliable = msg.get('reliable', False)
                total_bytes = message_wire_payload_size(msg, type_mappings)
                f.write(f"### `{msg['name']}` — ID `{msg['id']:#04x}`\n\n")
                _write_message_meta(f, msg, 'sub_topic')
                f.write(f"- **数据段字节数（Len）**：`{total_bytes}`\n")
                if msg.get('notes'):
                    f.write(f"- **注意事项**：{msg['notes']}\n")
                if msg['name'] == 'Handshake' and require_handshake:
                    f.write("- **内置行为**：协议层收到握手包后自动回传本机 `PROTOCOL_HASH`，是否匹配由 ROS 端校验，MCU 侧无需编写代码。\n")
                if msg['name'] == 'Heartbeat':
                    f.write(f"- **内置行为**：ROS 端每 `{heartbeat_interval_ms} ms` 发起一次心跳，协议层自动按原样回传同一个 `count` 作为 ACK，MCU 侧无需编写代码。\n")
                if reliable:
                    f.write("- **可靠投递**：该消息启用 ACK/重传。ROS 端会在业务结构体 payload 后透明追加 1 字节 reliable seq；"
                            "该字节参与 `Len` 和校验，但不属于 `Packet_xxx` 业务结构体字段。生成的分发逻辑会先调用 `on_receive_xxx()`，回调返回后再自动 `send_Ack()`。\n")
                    f.write("- **投递语义**：ROS 节点进程存活期间的链路级 at-least-once。同 ID 消息按 FIFO 发送，ACK 丢失或串口断连重连时 ROS 端会持续重传到收到匹配 ACK；节点进程崩溃后的恢复不在保证范围内。`on_receive_xxx()` 可能被重复调用，回调实现需保证幂等。\n")
                f.write("\n")
                f.write(_field_table(
                    msg['fields'],
                    type_mappings,
                    checksum,
                    include_reliable_seq=reliable,
                ))
                f.write("\n\n")
        else:
            f.write("_无_\n\n")

        f.write("---\n\n")
        f.write("*文档由构建系统自动生成，版本以协议哈希为准。*\n")

        write_generated_file(output_path, f.getvalue())


# ---------------------------------------------------------------------------
# 校验
# ---------------------------------------------------------------------------

def validate_protocol(config_data):
    """验证协议配置的完整性和合法性。

    只校验用户 YAML 中的业务消息；系统消息由生成器注入，禁止在 YAML 中出现。
    """
    if not isinstance(config_data, dict):
        raise ValueError("Protocol YAML root must be a mapping.")

    cfg = config_data.get('config', {})
    messages = config_data.get('messages', [])
    type_mappings = config_data.get('type_mappings', {})
    serial_params = config_data.get('serial_controller', {}).get('ros__parameters', {})
    errors = []

    if not isinstance(cfg, dict):
        errors.append("Top-level 'config' must be a mapping.")
        cfg = {}
    if messages is None:
        messages = []
        config_data['messages'] = messages
    if not isinstance(messages, list):
        errors.append("Top-level 'messages' must be a list.")
        messages = []
    if not isinstance(type_mappings, dict):
        errors.append("Top-level 'type_mappings' must be a mapping.")
        type_mappings = {}
    if not isinstance(serial_params, dict):
        errors.append("serial_controller.ros__parameters must be a mapping.")
        serial_params = {}

    if 'baudrate' in cfg:
        errors.append("config.baudrate is not supported; use serial_controller.ros__parameters.baudrate only.")
    baudrate = serial_params.get('baudrate')
    if not isinstance(baudrate, int) or isinstance(baudrate, bool) or baudrate <= 0:
        errors.append("serial_controller.ros__parameters.baudrate must be a positive integer.")
    port = serial_params.get('port')
    if not isinstance(port, str) or not port:
        errors.append("serial_controller.ros__parameters.port must be a non-empty string.")

    identifier_re = re.compile(r'^[A-Za-z_][A-Za-z0-9_]*$')
    ros_msg_re = re.compile(r'^[a-z][a-z0-9_]*/msg/[A-Z][A-Za-z0-9_]*$')
    topic_re = re.compile(r'^(?!/)(?!.*//)[A-Za-z0-9_~][A-Za-z0-9_~/]*$')
    supported_c_types = set(_C_TYPE_SIZES)

    SUPPORTED_CHECKSUMS = {"NONE", "SUM8", "XOR8", "CRC8"}
    checksum_algo = str(cfg.get('checksum', 'CRC8')).upper()
    if checksum_algo not in SUPPORTED_CHECKSUMS:
        errors.append(f"Unsupported checksum '{cfg.get('checksum')}'. Supported: {', '.join(sorted(SUPPORTED_CHECKSUMS))}")
    cfg['checksum'] = checksum_algo

    for key in ('head_byte_1', 'head_byte_2'):
        value = cfg.get(key)
        if not isinstance(value, int) or isinstance(value, bool) or not 0 <= value <= 0xFF:
            errors.append(f"config.{key} must be an integer in [0, 255].")

    buffer_size = cfg.get('buffer_size')
    if not isinstance(buffer_size, int) or isinstance(buffer_size, bool) or buffer_size <= 0:
        errors.append("config.buffer_size must be a positive integer.")

    if 'enable_heartbeat' in cfg:
        errors.append(
            "config.enable_heartbeat is no longer supported; heartbeat is always enabled. "
            "Tune heartbeat_interval_ms / heartbeat_timeout_ms / strict_heartbeat instead."
        )

    for key in ('require_handshake', 'ignore_version_mismatch', 'strict_heartbeat'):
        if not isinstance(cfg.get(key, True), bool):
            errors.append(f"config.{key} must be boolean.")

    for key, default in (
        ('heartbeat_interval_ms', 1000),
        ('heartbeat_timeout_ms', 3000),
        ('reliable_retry_interval_ms', 100),
        ('reliable_max_retries', 3),
        ('qos_depth', 10),
    ):
        value = cfg.get(key, default)
        if not isinstance(value, int) or isinstance(value, bool) or value <= 0:
            errors.append(f"config.{key} must be a positive integer.")

    heartbeat_interval = cfg.get('heartbeat_interval_ms', 1000)
    heartbeat_timeout = cfg.get('heartbeat_timeout_ms', 3000)
    if (
        isinstance(heartbeat_interval, int) and not isinstance(heartbeat_interval, bool)
        and isinstance(heartbeat_timeout, int) and not isinstance(heartbeat_timeout, bool)
        and heartbeat_interval > 0 and heartbeat_timeout > 0
        and heartbeat_timeout < heartbeat_interval
    ):
        errors.append(
            f"config.heartbeat_timeout_ms={heartbeat_timeout} must be >= "
            f"heartbeat_interval_ms={heartbeat_interval}."
        )

    VALID_DIRECTIONS = {"tx", "rx", "both"}
    VALID_DEBUG_LOG_MODES = {"on", "off"}
    seen_ids = {}
    seen_names = set()
    seen_generated_symbols = {name.upper(): name for name in SYSTEM_MESSAGE_NAMES}
    seen_sub_topics = {}
    seen_pub_topics = {}

    for i, msg in enumerate(messages):
        if not isinstance(msg, dict):
            errors.append(f"messages[{i}] must be a mapping.")
            continue
        label = msg.get('name', f'messages[{i}]')

        for required in ('name', 'id', 'direction', 'ros_msg', 'fields'):
            if required not in msg:
                errors.append(f"Message '{label}' missing required field '{required}'.")

        if msg.get('direction') not in VALID_DIRECTIONS:
            errors.append(f"Message '{label}' has invalid direction '{msg.get('direction')}'. Must be one of: {', '.join(sorted(VALID_DIRECTIONS))}")

        debug_log_mode = _normalize_debug_log_mode(msg.get('debug_log_mode', 'on'))
        if debug_log_mode not in VALID_DEBUG_LOG_MODES:
            errors.append(
                f"Message '{label}' has invalid debug_log_mode '{msg.get('debug_log_mode')}'. Must be one of: {', '.join(sorted(VALID_DEBUG_LOG_MODES))}."
            )
        else:
            msg['debug_log_mode'] = debug_log_mode

        if 'reliable' in msg and not isinstance(msg.get('reliable'), bool):
            errors.append(f"Message '{label}' has invalid reliable='{msg.get('reliable')}'. Must be boolean.")

        if msg.get('reliable', False) and msg.get('direction') != 'tx':
            errors.append(
                f"Message '{label}' sets reliable=true but direction is '{msg.get('direction')}'. "
                "reliable is only supported for direction 'tx' (ROS -> MCU)."
            )

        mid = msg.get('id')
        if mid is not None:
            if not isinstance(mid, int) or isinstance(mid, bool) or not 0 <= mid <= 0xFF:
                errors.append(f"Message '{label}' id must be an integer in [0, 255].")
            elif mid in RESERVED_IDS:
                errors.append(
                    f"Message '{label}' uses reserved ID {mid:#04x}. IDs 0xFD-0xFF belong to built-in "
                    f"system message '{RESERVED_IDS[mid]}'; system messages are injected automatically "
                    "and must not appear in protocol.yaml."
                )
            elif mid in seen_ids:
                errors.append(f"Message '{label}' has duplicate ID {mid:#04x} (conflicts with '{seen_ids[mid]}').")
            else:
                seen_ids[mid] = label

        name = msg.get('name')
        if name is not None:
            if not isinstance(name, str) or not identifier_re.fullmatch(name):
                errors.append(f"Message name '{name}' must be a valid C identifier.")
            elif name in SYSTEM_MESSAGE_NAMES:
                errors.append(
                    f"Message name '{name}' is reserved for a built-in system message; "
                    "remove it from protocol.yaml (system messages are injected automatically)."
                )
            elif name in seen_names:
                errors.append(f"Duplicate message name '{name}'.")
            else:
                seen_names.add(name)
                generated_symbol = name.upper()
                if generated_symbol in seen_generated_symbols:
                    errors.append(
                        f"Message '{name}' generated symbol PACKET_ID_{generated_symbol} conflicts with "
                        f"'{seen_generated_symbols[generated_symbol]}'."
                    )
                else:
                    seen_generated_symbols[generated_symbol] = name

        ros_msg = msg.get('ros_msg')
        if not isinstance(ros_msg, str) or not ros_msg_re.fullmatch(ros_msg):
            errors.append(f"Message '{label}' has invalid ros_msg '{ros_msg}'. Expected package/msg/Type.")

        direction = msg.get('direction', '')
        if direction in ('tx', 'both') and 'sub_topic' not in msg:
            errors.append(f"Message '{label}' (direction={direction}) missing 'sub_topic'.")
        if direction in ('rx', 'both') and 'pub_topic' not in msg:
            errors.append(f"Message '{label}' (direction={direction}) missing 'pub_topic'.")

        for topic_key in ('sub_topic', 'pub_topic'):
            if topic_key not in msg:
                continue
            topic = msg.get(topic_key)
            if not isinstance(topic, str) or not topic_re.fullmatch(topic):
                errors.append(
                    f"Message '{label}' has invalid {topic_key} '{topic}'. Use a non-empty relative ROS topic."
                )

        sub_topic = msg.get('sub_topic')
        pub_topic = msg.get('pub_topic')
        if direction == 'both' and sub_topic and pub_topic and sub_topic == pub_topic:
            errors.append(
                f"Message '{label}' uses the same topic '{sub_topic}' for sub_topic and pub_topic; "
                "this would loop MCU traffic back to the MCU. Use two different topics."
            )
        if isinstance(sub_topic, str):
            if sub_topic in seen_sub_topics:
                errors.append(f"Message '{label}' reuses sub_topic '{sub_topic}' (already used by '{seen_sub_topics[sub_topic]}').")
            else:
                seen_sub_topics[sub_topic] = label
        if isinstance(pub_topic, str):
            if pub_topic in seen_pub_topics:
                errors.append(f"Message '{label}' reuses pub_topic '{pub_topic}' (already used by '{seen_pub_topics[pub_topic]}').")
            else:
                seen_pub_topics[pub_topic] = label

        fields = msg.get('fields', [])
        if not isinstance(fields, list):
            errors.append(f"Message '{label}' fields must be a list.")
            fields = []
        elif 'fields' in msg and not fields:
            errors.append(f"Message '{label}' must declare at least one field.")
        seen_fields = set()
        for field in fields:
            if not isinstance(field, dict):
                errors.append(f"Message '{label}' contains a field that is not a mapping.")
                continue
            field_name = field.get('proto')
            if not isinstance(field_name, str) or not identifier_re.fullmatch(field_name):
                errors.append(f"Message '{label}' field name '{field_name}' must be a valid C identifier.")
            elif is_reserved_c_cpp_identifier(field_name):
                errors.append(
                    f"Message '{label}' field name '{field_name}' is reserved by C/C++."
                )
            elif field_name in seen_fields:
                errors.append(f"Message '{label}' has duplicate field name '{field_name}'.")
            else:
                seen_fields.add(field_name)
            ftype = field.get('type', '')
            c_type = get_c_type(ftype, type_mappings)
            if c_type not in supported_c_types:
                errors.append(f"Message '{label}', field '{field.get('proto', '?')}': unknown type '{ftype}'.")
            ros_path = field.get('ros')
            if not isinstance(ros_path, str) or not ros_path:
                errors.append(f"Message '{label}', field '{field.get('proto', '?')}' missing non-empty ros path.")
            else:
                try:
                    _analyze_ros_path(ros_path, 'msg', True)
                except ValueError as exc:
                    errors.append(f"Message '{label}', field '{field.get('proto', '?')}': {exc}")

        if fields:
            wire_size = message_wire_payload_size(msg, type_mappings)
            if wire_size > 0xFF:
                errors.append(f"Message '{label}' wire payload is {wire_size} bytes; maximum is 255.")

    if isinstance(buffer_size, int) and not isinstance(buffer_size, bool) and buffer_size > 0:
        sizable = [
            m for m in messages
            if isinstance(m, dict) and isinstance(m.get('id'), int) and isinstance(m.get('fields'), list)
        ]
        all_messages = merge_messages({'messages': sizable})
        largest_frame = max(
            message_wire_payload_size(msg, type_mappings) + 5
            for msg in all_messages
        )
        if buffer_size < largest_frame:
            errors.append(
                f"config.buffer_size={buffer_size} cannot hold the largest complete frame ({largest_frame} bytes)."
            )

    if errors:
        print("Protocol validation failed:", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        sys.exit(1)


# ---------------------------------------------------------------------------
# 入口
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Generate Auto Serial Bridge protocol sources.")
    parser.add_argument('protocol_yaml')
    parser.add_argument('output_dir', nargs='?')
    parser.add_argument(
        '--print-ros-packages',
        action='store_true',
        help='validate YAML and print referenced ROS message packages, one per line',
    )
    args = parser.parse_args()
    if not args.print_ros_packages and not args.output_dir:
        parser.error('output_dir is required unless --print-ros-packages is used')

    with open(args.protocol_yaml, 'r', encoding='utf-8') as f:
        config_data = yaml.safe_load(f.read())

    validate_protocol(config_data)

    if args.print_ros_packages:
        print('\n'.join(ros_message_packages(config_data)))
        return

    config = config_data['config']
    type_mappings = config_data.get('type_mappings', {}) or {}
    serial_params = config_data.get('serial_controller', {}).get('ros__parameters', {})
    messages = merge_messages(config_data)
    phash = calculate_protocol_hash(config_data)

    generated_dir = os.path.join(args.output_dir, 'generated')
    mcu_header_path = os.path.join(generated_dir, 'protocol.h')
    mcu_source_path = os.path.join(generated_dir, 'protocol.c')

    generate_mcu_header(config, messages, type_mappings, phash,
                        mcu_header_path, extract_user_code(mcu_header_path))
    generate_mcu_source(config, messages, type_mappings,
                        mcu_source_path, extract_user_code(mcu_source_path))
    generate_cpp_config(config, messages, type_mappings,
                        os.path.join(generated_dir, 'generated_config.hpp'),
                        serial_params)
    generate_ros_bindings(messages, type_mappings, config,
                          os.path.join(generated_dir, 'generated_bindings.hpp'))
    generate_mcu_doc(config, messages, type_mappings, phash,
                     os.path.join(generated_dir, 'PROTOCOL_DOC.md'),
                     serial_params)


if __name__ == "__main__":
    main()
